# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f85a2835ea1446f791ec7bcbf84320ed7098eb491f2191ec134a52cd569bc89ad48e8996610e6d9f45b8bcb2a5f4729c7f826617c354edb5388e792df3edc6f

test:
  secret_key_base: 2ac5e06bbf60ee053a8ef17af0bcf1727da25f29d1a7cbe8f6732245f9ce568af8cf68c9b50cf861ab9a2ed55ce99c21ebef5a470ced2a5405981f9dc3cf0159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
